/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomePageRouteImport } from './routes/home/page'
import { Route as HomeUsersPageRouteImport } from './routes/home/users/page'
import { Route as HomeInboxPageRouteImport } from './routes/home/inbox/page'
import { Route as HomeCoursesPageRouteImport } from './routes/home/courses/page'
import { Route as HomeCoursesCreateRouteImport } from './routes/home/courses/create'
import { Route as HomeBackendPageRouteImport } from './routes/home/backend/page'
import { Route as HomeAssignmentsPageRouteImport } from './routes/home/assignments/page'
import { Route as HomeCoursesEditCourseIdRouteImport } from './routes/home/courses/edit/$courseId'
import { Route as HomeCoursesDeleteCourseIdRouteImport } from './routes/home/courses/delete/$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePageRoute = HomePageRouteImport.update({
  id: '/home/page',
  path: '/home/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeUsersPageRoute = HomeUsersPageRouteImport.update({
  id: '/home/users/page',
  path: '/home/users/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeInboxPageRoute = HomeInboxPageRouteImport.update({
  id: '/home/inbox/page',
  path: '/home/inbox/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCoursesPageRoute = HomeCoursesPageRouteImport.update({
  id: '/home/courses/page',
  path: '/home/courses/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCoursesCreateRoute = HomeCoursesCreateRouteImport.update({
  id: '/home/courses/create',
  path: '/home/courses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBackendPageRoute = HomeBackendPageRouteImport.update({
  id: '/home/backend/page',
  path: '/home/backend/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAssignmentsPageRoute = HomeAssignmentsPageRouteImport.update({
  id: '/home/assignments/page',
  path: '/home/assignments/page',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCoursesEditCourseIdRoute = HomeCoursesEditCourseIdRouteImport.update({
  id: '/home/courses/edit/$courseId',
  path: '/home/courses/edit/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCoursesDeleteCourseIdRoute =
  HomeCoursesDeleteCourseIdRouteImport.update({
    id: '/home/courses/delete/$courseId',
    path: '/home/courses/delete/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/page': typeof HomePageRoute
  '/home/assignments/page': typeof HomeAssignmentsPageRoute
  '/home/backend/page': typeof HomeBackendPageRoute
  '/home/courses/create': typeof HomeCoursesCreateRoute
  '/home/courses/page': typeof HomeCoursesPageRoute
  '/home/inbox/page': typeof HomeInboxPageRoute
  '/home/users/page': typeof HomeUsersPageRoute
  '/home/courses/delete/$courseId': typeof HomeCoursesDeleteCourseIdRoute
  '/home/courses/edit/$courseId': typeof HomeCoursesEditCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/page': typeof HomePageRoute
  '/home/assignments/page': typeof HomeAssignmentsPageRoute
  '/home/backend/page': typeof HomeBackendPageRoute
  '/home/courses/create': typeof HomeCoursesCreateRoute
  '/home/courses/page': typeof HomeCoursesPageRoute
  '/home/inbox/page': typeof HomeInboxPageRoute
  '/home/users/page': typeof HomeUsersPageRoute
  '/home/courses/delete/$courseId': typeof HomeCoursesDeleteCourseIdRoute
  '/home/courses/edit/$courseId': typeof HomeCoursesEditCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/page': typeof HomePageRoute
  '/home/assignments/page': typeof HomeAssignmentsPageRoute
  '/home/backend/page': typeof HomeBackendPageRoute
  '/home/courses/create': typeof HomeCoursesCreateRoute
  '/home/courses/page': typeof HomeCoursesPageRoute
  '/home/inbox/page': typeof HomeInboxPageRoute
  '/home/users/page': typeof HomeUsersPageRoute
  '/home/courses/delete/$courseId': typeof HomeCoursesDeleteCourseIdRoute
  '/home/courses/edit/$courseId': typeof HomeCoursesEditCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/page'
    | '/home/assignments/page'
    | '/home/backend/page'
    | '/home/courses/create'
    | '/home/courses/page'
    | '/home/inbox/page'
    | '/home/users/page'
    | '/home/courses/delete/$courseId'
    | '/home/courses/edit/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/page'
    | '/home/assignments/page'
    | '/home/backend/page'
    | '/home/courses/create'
    | '/home/courses/page'
    | '/home/inbox/page'
    | '/home/users/page'
    | '/home/courses/delete/$courseId'
    | '/home/courses/edit/$courseId'
  id:
    | '__root__'
    | '/'
    | '/home/page'
    | '/home/assignments/page'
    | '/home/backend/page'
    | '/home/courses/create'
    | '/home/courses/page'
    | '/home/inbox/page'
    | '/home/users/page'
    | '/home/courses/delete/$courseId'
    | '/home/courses/edit/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomePageRoute: typeof HomePageRoute
  HomeAssignmentsPageRoute: typeof HomeAssignmentsPageRoute
  HomeBackendPageRoute: typeof HomeBackendPageRoute
  HomeCoursesCreateRoute: typeof HomeCoursesCreateRoute
  HomeCoursesPageRoute: typeof HomeCoursesPageRoute
  HomeInboxPageRoute: typeof HomeInboxPageRoute
  HomeUsersPageRoute: typeof HomeUsersPageRoute
  HomeCoursesDeleteCourseIdRoute: typeof HomeCoursesDeleteCourseIdRoute
  HomeCoursesEditCourseIdRoute: typeof HomeCoursesEditCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/page': {
      id: '/home/page'
      path: '/home/page'
      fullPath: '/home/page'
      preLoaderRoute: typeof HomePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/users/page': {
      id: '/home/users/page'
      path: '/home/users/page'
      fullPath: '/home/users/page'
      preLoaderRoute: typeof HomeUsersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/inbox/page': {
      id: '/home/inbox/page'
      path: '/home/inbox/page'
      fullPath: '/home/inbox/page'
      preLoaderRoute: typeof HomeInboxPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/courses/page': {
      id: '/home/courses/page'
      path: '/home/courses/page'
      fullPath: '/home/courses/page'
      preLoaderRoute: typeof HomeCoursesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/courses/create': {
      id: '/home/courses/create'
      path: '/home/courses/create'
      fullPath: '/home/courses/create'
      preLoaderRoute: typeof HomeCoursesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/backend/page': {
      id: '/home/backend/page'
      path: '/home/backend/page'
      fullPath: '/home/backend/page'
      preLoaderRoute: typeof HomeBackendPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/assignments/page': {
      id: '/home/assignments/page'
      path: '/home/assignments/page'
      fullPath: '/home/assignments/page'
      preLoaderRoute: typeof HomeAssignmentsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/courses/edit/$courseId': {
      id: '/home/courses/edit/$courseId'
      path: '/home/courses/edit/$courseId'
      fullPath: '/home/courses/edit/$courseId'
      preLoaderRoute: typeof HomeCoursesEditCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/courses/delete/$courseId': {
      id: '/home/courses/delete/$courseId'
      path: '/home/courses/delete/$courseId'
      fullPath: '/home/courses/delete/$courseId'
      preLoaderRoute: typeof HomeCoursesDeleteCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomePageRoute: HomePageRoute,
  HomeAssignmentsPageRoute: HomeAssignmentsPageRoute,
  HomeBackendPageRoute: HomeBackendPageRoute,
  HomeCoursesCreateRoute: HomeCoursesCreateRoute,
  HomeCoursesPageRoute: HomeCoursesPageRoute,
  HomeInboxPageRoute: HomeInboxPageRoute,
  HomeUsersPageRoute: HomeUsersPageRoute,
  HomeCoursesDeleteCourseIdRoute: HomeCoursesDeleteCourseIdRoute,
  HomeCoursesEditCourseIdRoute: HomeCoursesEditCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
